language: python
python:
- '2.7'
install: pip install -r requirements.txt
notifications:
  slack:
    secure: hHYCBWVDDKwAqPizGboX7dqeQsVNBJ31Q0Hr/mn+cBEf1nxcjq08FGG3SC2MBtWXBTFCbiOvQT9upR8r2TFIIj5wJ5OSzsTXGL1CmM3PyyMU5TcADjKM39ujElprYn1nEBQIRYCF11wmaRHhm8dVbHTl1Tmnm1DEDZmAjhIkzw0=
script: python test.py
