language: python
python:
- '2.7'
install: pip install -r requirements.txt
notifications:
  slack:
    secure: PXpykvxCaYkERCatpqKlHSlxy9S1nU5eRrh8aAA1YAsgI6XNdBtljss7R+eZwqNlXee5B+tmsUmD7VEjozM8lkmmSMn4930y38MhiIButVaHEOC2lLlVYVfn6pk0me8f+/BYlBR2Sba70jy1lFIdfE+cJPHHahauP7A6esMaO70=
script: python test.py
